name: Test Borg Backup

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          sudo apt install expect
          sudo add-apt-repository ppa:costamagnagianfranco/borgbackup --yes
          sudo apt update -qq
          sudo apt install borgbackup
          cd test
          ./expectBorgDrive.sh
          if [ $? -eq 1 ]
          then
            exit 1
