name: Test Linux Mint

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set environment variables and run script
        run: |
           export GITHUB_USER_NAME="Mickey Mouse"
           export GITHUB_USER_EMAIL="mickey@emailsim.io"
           ./linuxMint.sh
