name: Test Restic Backup

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          sudo apt install expect
          sudo apt install restic
          cd test
          ./expectResticDrive.sh
          if [ $? -eq 1 ]
          then
            exit 1
